# Generated by Django 5.0.7 on 2024-08-09 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnostic', models.DateField(default=django.utils.timezone.now)),
                ('resultat', models.TextField()),
                ('prescription', models.CharField(choices=[('Examen', 'Examen'), ('Medicament', 'Médicament')], max_length=10)),
                ('details', models.TextField()),
                ('nom_docteur', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
