# Generated by Django 5.0.7 on 2024-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='nom_docteur',
            field=models.CharField(max_length=200),
        ),
    ]
