# Generated by Django 5.0.7 on 2024-08-13 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_diagnostic_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendezvous', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree', models.DurationField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('centre_de_sante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.centredesante')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
